package bbtracker;
import com.toedter.calendar.JDateChooser;
import java.awt.Toolkit;
import javax.swing.*;
import java.io.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.*;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.time.LocalDate;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mikaella Gonzales
 */
public class AddExpense extends javax.swing.JFrame {
    private Login login;

    public AddExpense(Login login) {
        this.login = login;
        // Initialize components
    }

    public AddExpense() {
        initComponents();
        setIconImage(); 
    }
    
    private void setIconImage(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/icon_img.png")));
    }  

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Bills", "Transportation", "Dormitory", "Shopping", "Healthcare", "Others", " ", " " }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.setFocusable(false);
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 310, 45));

        jLabel2.setText("Catergoies");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel3.setText("Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jTextField1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jTextField1.setMinimumSize(new java.awt.Dimension(111, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(111, 22));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 310, 45));

        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jDateChooser1.setBackground(new java.awt.Color(0, 102, 102));
        jDateChooser1.setDateFormatString("MM/d/ yy");
        jDateChooser1.setFocusable(false);
        jDateChooser1.setOpaque(false);
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 313, 45));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Transactions");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 313, 45));

        jLabel5.setText("History");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bbtracker/add.png"))); // NOI18N
        jButton2.setText("Add Expense");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 146, 52));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/history.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, 60));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btns/bin.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Expense");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addExpense.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_bg.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        double expenseAmount;
        String expenseCategory = (String) jComboBox1.getSelectedItem();
        String username = Login.jTextField1.getText();

       
        try {
            expenseAmount = Double.parseDouble(jTextField1.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid amount format.");
            return;
        }

      
        Date selectedDate = jDateChooser1.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(null, "Please select a date.");
            return; 
        }

       
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(selectedDate);

        
        String fileName = username + "_expenses.txt";
        File expensesFile = new File(fileName);

       
        Map<String, Map<String, List<Double>>> dateToCategoryExpensesMap = new LinkedHashMap<>();

       
        if (expensesFile.exists()) {
            try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
                String line;
                String currentDate = null;
                String currentCategory = null;

                while ((line = reader.readLine()) != null) {
                    if (line.startsWith("Transaction:")) {
                        continue; 
                    } else if (line.equals("--------------------------------------------------")) {
                        continue;  
                    } else if (line.trim().matches("\\d{4}-\\d{2}-\\d{2}")) {
                        currentDate = line.trim();
                        dateToCategoryExpensesMap.putIfAbsent(currentDate, new LinkedHashMap<>()); 
                    } else if (line.trim().matches("\\d+(\\.\\d+)?, .+")) {
                        String[] parts = line.split(", ");
                        if (parts.length == 2 && currentDate != null) {
                            double currentExpense = Double.parseDouble(parts[0]);
                            currentCategory = parts[1];
                            dateToCategoryExpensesMap.get(currentDate).putIfAbsent(currentCategory, new ArrayList<>()); 
                            dateToCategoryExpensesMap.get(currentDate).get(currentCategory).add(currentExpense); 
                        }
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error reading file: " + e.getMessage());
                return; 
            }
        }
        
        dateToCategoryExpensesMap.putIfAbsent(formattedDate, new LinkedHashMap<>());
        dateToCategoryExpensesMap.get(formattedDate).putIfAbsent(expenseCategory, new ArrayList<>());
        dateToCategoryExpensesMap.get(formattedDate).get(expenseCategory).add(expenseAmount);
        
        StringBuilder fileContent = new StringBuilder();
        int transactionNumber = 1;

        
        for (Map.Entry<String, Map<String, List<Double>>> dateEntry : dateToCategoryExpensesMap.entrySet()) {
            String date = dateEntry.getKey();
            Map<String, List<Double>> categoryToExpensesMap = dateEntry.getValue();

            fileContent.append("Transaction: ").append(transactionNumber++).append(System.lineSeparator());
            fileContent.append(date).append(System.lineSeparator());

            for (Map.Entry<String, List<Double>> categoryEntry : categoryToExpensesMap.entrySet()) {
                String currentCategory = categoryEntry.getKey();
                List<Double> expenses = categoryEntry.getValue();

                for (Double expense : expenses) {
                    fileContent.append(expense).append(", ").append(currentCategory).append(System.lineSeparator());
                }
            }

            fileContent.append("--------------------------------------------------").append(System.lineSeparator());
        }

        List<String> uniqueDates = new ArrayList<>(dateToCategoryExpensesMap.keySet());
        for (int i = 0; i < uniqueDates.size(); i += 7) {
            if (i + 7 <= uniqueDates.size()) {
                double periodTotal = 0.0;
                for (int j = i; j < i + 7; j++) {
                    String date = uniqueDates.get(j);
                    for (Map.Entry<String, List<Double>> categoryEntry : dateToCategoryExpensesMap.get(date).entrySet()) {
                        List<Double> expenses = categoryEntry.getValue();
                        for (Double expense : expenses) {
                            periodTotal += expense;
                        }
                    }
                }
                fileContent.append("Total for days ").append(uniqueDates.get(i)).append(" to ").append(uniqueDates.get(i + 6)).append(": ").append(periodTotal).append(System.lineSeparator());
                fileContent.append("--------------------------------------------------").append(System.lineSeparator());
            }
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            writer.write(fileContent.toString());
            JOptionPane.showMessageDialog(null, "Expense added successfully.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error writing to file: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed
 

    
 
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AddExpense addExpense = new AddExpense();
        addExpense.setVisible(true);
        addExpense.pack();
        addExpense.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Home home = new Home();
        home.setVisible(true);
        home.jLabel3.setText("@"+login.jTextField1.getText());
        home.pack();
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int option = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete all your expenses?","Confirmation", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            String username = Login.jTextField1.getText();
            String fileName = username + "_expenses.txt";

        File deleteExpenses = new File(fileName);

            if (deleteExpenses.exists()) {
                boolean deleted = deleteExpenses.delete();
                if (deleted) {
                    JOptionPane.showMessageDialog(this,"All expenses deleted successfully.", "File Deleted", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete your expenses.","Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,"No expenses.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String username = Login.jTextField1.getText();
        String fileName = username + "_expenses.txt";

        List<TransactionList.Transaction> transactions = new ArrayList<>();
        TransactionList.Transaction currentTransaction = null;

        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith("Transaction:")) {
                    if (currentTransaction != null) {
                        transactions.add(currentTransaction);
                    }
                    String date = br.readLine().trim();
                    currentTransaction = new TransactionList.Transaction(date);
                } else if (line.matches("^\\d+\\.\\d+, .+$")) {
                    String[] parts = line.split(", ");
                    try {
                        double amount = Double.parseDouble(parts[0]);
                        String description = parts[1];
                        currentTransaction.addTransaction(amount, description);
                    } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
                        JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            
            if (currentTransaction != null) {
                transactions.add(currentTransaction);
            }
        } catch (IOException e) {
             JOptionPane.showMessageDialog(null, "No transactions found.", "Message", JOptionPane.INFORMATION_MESSAGE);
        }

        SwingUtilities.invokeLater(() -> new TransactionList.TransactionListGUI(transactions));

        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String username = Login.jTextField1.getText();
        String fileName = username + "_expenses.txt";
        List<BubbleUp.Transaction> transactions = BubbleUp.readTransactionsFromFile(fileName);

        BubbleUp bubbleUp = new BubbleUp();
        bubbleUp.setVisible(true);
        bubbleUp.displayOutput(transactions);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = Login.jTextField1.getText();
        String fileName = username + "_expenses.txt";
    
        List<UserExpense.Transaction> transactions = new ArrayList<>();
        UserExpense.Transaction currentTransaction = null;

        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith("Transaction:")) {
                    if (currentTransaction != null) {
                        transactions.add(currentTransaction);
                    }
                    String date = br.readLine().trim();
                    currentTransaction = new UserExpense.Transaction(date);
                } else if (line.matches("^\\d+\\.\\d+, .+$")) {
                    String[] parts = line.split(", ");
                    try {
                        double amount = Double.parseDouble(parts[0]);
                        String description = parts[1];
                        currentTransaction.addTransaction(amount, description);
                    } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
                        JOptionPane.showMessageDialog(null, "Failed to load", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } 
            if (currentTransaction != null) {
                transactions.add(currentTransaction);
            }
           
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Failed to load", "Error", JOptionPane.ERROR_MESSAGE);
        }

        SwingUtilities.invokeLater(() -> new UserExpense.TransactionListGUI(transactions));

        this.dispose();  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddExpense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
